export const schemaStatements = [
  `CREATE TABLE IF NOT EXISTS "JobPost" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "title" TEXT NOT NULL,
    "internalName" TEXT,
    "department" TEXT,
    "category" TEXT,
    "location" TEXT,
    "secondaryLocation" TEXT,
    "positionType" TEXT,
    "salaryRange" TEXT,
    "reportsTo" TEXT,
    "positionCode" TEXT,
    "seatCode" TEXT,
    "travelPercentage" TEXT,
    "educationLevel" TEXT,
    "workSchedule" TEXT,
    "summary" TEXT,
    "keyResponsibilities" TEXT,
    "qualificationsText" TEXT,
    "benefitsText" TEXT,
    "postedDate" DATETIME,
    "status" TEXT NOT NULL DEFAULT 'DRAFT',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS "PaycomConfig" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "jobPostId" TEXT NOT NULL,
    "workflow" TEXT,
    "externalApplication" TEXT,
    "externalKnockout" TEXT,
    "externalGlobal" TEXT,
    "externalJobLevel" TEXT,
    "externalFollowUps" TEXT,
    "internalApplication" TEXT,
    "internalKnockout" TEXT,
    "internalGlobal" TEXT,
    "internalJobLevel" TEXT,
    CONSTRAINT "PaycomConfig_jobPostId_fkey" FOREIGN KEY ("jobPostId") REFERENCES "JobPost" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "ContentBlock" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "category" TEXT NOT NULL,
    "scope" TEXT NOT NULL,
    "placement" TEXT NOT NULL DEFAULT 'OPTIONAL',
    "currentVersionId" TEXT,
    "archivedAt" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS "ContentBlockVersion" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "contentBlockId" TEXT NOT NULL,
    "versionNumber" INTEGER NOT NULL,
    "title" TEXT NOT NULL,
    "body" TEXT NOT NULL,
    "plainText" TEXT,
    "bodyFormat" TEXT NOT NULL DEFAULT 'BULLET_LIST',
    "textWeight" TEXT NOT NULL DEFAULT 'NORMAL',
    "textColor" TEXT NOT NULL DEFAULT 'BLACK',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "changeNote" TEXT,
    CONSTRAINT "ContentBlockVersion_contentBlockId_fkey" FOREIGN KEY ("contentBlockId") REFERENCES "ContentBlock" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "JobBlockInstance" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "jobPostId" TEXT NOT NULL,
    "contentBlockId" TEXT,
    "blockVersionId" TEXT,
    "sortOrder" INTEGER NOT NULL,
    "sectionKey" TEXT NOT NULL,
    "mode" TEXT NOT NULL DEFAULT 'LINKED',
    "customTitle" TEXT,
    "customBody" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "JobBlockInstance_jobPostId_fkey" FOREIGN KEY ("jobPostId") REFERENCES "JobPost" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "JobBlockInstance_contentBlockId_fkey" FOREIGN KEY ("contentBlockId") REFERENCES "ContentBlock" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "JobBlockInstance_blockVersionId_fkey" FOREIGN KEY ("blockVersionId") REFERENCES "ContentBlockVersion" ("id") ON DELETE SET NULL ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "Template" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "isLocked" BOOLEAN NOT NULL DEFAULT true,
    "version" INTEGER NOT NULL DEFAULT 1,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS "TemplateToken" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "templateId" TEXT NOT NULL,
    "key" TEXT NOT NULL,
    "value" TEXT NOT NULL,
    "locked" BOOLEAN NOT NULL DEFAULT true,
    CONSTRAINT "TemplateToken_templateId_fkey" FOREIGN KEY ("templateId") REFERENCES "Template" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "PaycomConfig_jobPostId_key" ON "PaycomConfig"("jobPostId")`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "ContentBlockVersion_contentBlockId_versionNumber_key" ON "ContentBlockVersion"("contentBlockId", "versionNumber")`
];
