/**
 * Guard for the Paycom notice classifier.
 *
 *   npx tsx scripts/paycom-notice-tests.ts
 *
 * READ ONLY — every case runs with dryRun: true, so nothing is ticked, tagged or
 * written. It does read the live new-hire roster, because matching against real
 * people is part of what is being tested.
 *
 * WHY THIS EXISTS, AND WHY IT IS NOT OPTIONAL
 *
 * Paycom sends FOUR offer notices about the same person, from the same address,
 * all of which contain "offer for NAME (id) to fill Requisition N":
 *
 *   "Pending Offer Approval"                    there IS a pending offer
 *   "ACTION REQUIRED: Pending Offer Approved"   ...has been APPROVED (internally)
 *   "Pending Offer Expires Soon"                ...expires soon
 *   "Offer Accepted"                            ...has been ACCEPTED  <- the only one
 *
 * Only the last means the candidate said yes. "Approved" is OUR approver signing
 * off, which happens before the offer even reaches the candidate. Dayten
 * Schureman's real sequence was Approval Aug 10, Approved Aug 10/13/14, Accepted
 * Aug 15 — so a pattern loosened to /offer.*approved/ or a bare /offer/ would
 * tick "Candidate signed offer letter" five days early, on a person who could
 * still decline. Nothing would throw. The checklist would simply be wrong, and a
 * recruiter would believe a signed offer was on file.
 *
 * Every body below is VERBATIM from Paycom's mail. The refusals matter more than
 * the acceptances: if you are here because you loosened a regex and this went
 * red, that is the test doing its job.
 *
 * The repo has no test runner, so this follows the pattern of
 * scripts/pilot-app-dry-run.ts — a script you run, exiting non-zero on failure so
 * it can be used as a gate.
 *
 * ENV: FRONT_API_TOKEN is not needed (nothing here talks to Front), but
 * DATABASE_URL is, and it lives in .env while .env.local holds everything else.
 * Both are loaded below, .env.local first so it wins.
 */
import { config } from "dotenv";
config({ path: ".env.local" });
config({ path: ".env" });

import { processPaycomMessage, type PaycomNoticeKind } from "../lib/paycom/notices";
import type { FrontMessage } from "../lib/front";
import { prisma } from "../lib/prisma";

function message(
  subject: string,
  text: string,
  from = "systemmessage@paycomonline.com",
  isInbound = true
): FrontMessage {
  return {
    id: `msg_test_${subject.length}_${text.length}`,
    is_inbound: isInbound,
    subject,
    text,
    recipients: [
      { handle: from, role: "from" },
      { handle: "aschaedig@skyshare.com", role: "to" }
    ]
  } as FrontMessage;
}

/** What a Front rule routing a Paycom notice into a shared inbox looks like when
    it forwards rather than moves: the original headers survive in the body. */
function forwarded(originalSubject: string, originalBody: string): string {
  return (
    "---------- Forwarded message ---------\n" +
    "From: Paycom <systemmessage@paycomonline.com>\n" +
    "Date: Sat, Aug 15, 2026 at 2:00 PM\n" +
    `Subject: ${originalSubject}\n` +
    "To: <aschaedig@skyshare.com>\n\n" +
    originalBody
  );
}

const ACCEPTED_BODY =
  "SKYSHARE 16856 Offer Accepted Hello Aimee Schaedig, The offer for Dayten Schureman (333520) to fill " +
  "Requisition 3685 has been accepted. This offer was for the Gulfstream G200 First Officer position. " +
  "Log in to Paycom to view. This notice was automatically generated by paycomonline.com.";

const APPROVED_BODY =
  "SKYSHARE 16856 ACTION REQUIRED: Pending Offer Approved Hello Aimee, A pending offer for Dayten " +
  "Schureman (333520) to fill requisition 3685 has been approved. This offer is for the Gulfstream G200 " +
  "First Officer position. This notice was automatically generated by paycomonline.com.";

/**
 * "Recognised" outcomes — the notice was identified and the app went on to try to
 * place it. Whether it then ticked, found the step already done, or failed to
 * match a person depends on live roster data.
 *
 * ASSERTING ON THIS RATHER THAN ON "ticked" IS DELIBERATE. A test that demanded
 * would-tick would go red the day Dayten Schureman is ticked for real (he now is)
 * or leaves the roster — failures that say nothing about the parser. What this
 * file exists to protect is the CLASSIFICATION: that the right notice is
 * recognised and the three lookalikes are refused.
 */
const RECOGNISED = new Set(["would-tick", "ticked", "already-done", "no-match", "ambiguous-match", "no-such-task"]);

type Case = {
  label: string;
  message: FrontMessage;
  /** Expect the notice to be recognised and acted on, or refused outright. */
  expect: "recognise" | "refuse";
  /** The notice it must be identified as, when recognised. */
  kind?: PaycomNoticeKind;
  /** Assert the exact outcome, where WHICH refusal matters. */
  outcome?: string;
};

const CASES: Case[] = [
  // ---------- the real thing, both wordings Paycom has used ----------
  {
    label: "Offer Accepted, current wording (Dayten Schureman, 2026-08-15)",
    expect: "recognise",
    kind: "OFFER_ACCEPTED",
    message: message(
      "Offer Accepted",
      "| | |\n| # SKYSHARE ## 16856 |\n\n| | ## Offer Accepted\n\n| Hello Aimee Schaedig, The offer for " +
        "Dayten Schureman (333520) to fill Requisition 3685 has been accepted. This offer was for the " +
        "Gulfstream G200 First Officer position. Log in to Paycom to view. |"
    )
  },
  {
    label: "Offer Accepted, older wording (Bailey Barcelon, 2025-12-19)",
    expect: "recognise",
    kind: "OFFER_ACCEPTED",
    message: message(
      "Offer Accepted",
      " &nbsp\n\n| | ## Offer Accepted\n\n| Hello Aimee Schaedig, You have an offer for Bailey Barcelon " +
        "(151908) filling Requisition 2233 that has been accepted. This offer is for the Citation 560XL " +
        "First Officer position. Log in to Paycom to view. |"
    )
  },

  // ---------- THE COLLISION. These three must never tick. ----------
  {
    label: "Pending Offer Approved — OUR approver, days before acceptance",
    expect: "refuse",
    outcome: "not-actionable",
    message: message(
      "ACTION REQUIRED: Pending Offer Approved",
      "| | ## ACTION REQUIRED: Pending Offer Approved\n\n| Hello Aimee, A pending offer for Dayten " +
        "Schureman (333520) to fill requisition 3685 has been approved. This offer is for the Gulfstream " +
        "G200 First Officer position. You can send this offer to the applicant now. |"
    )
  },
  {
    label: "Pending Offer Approval — not even approved yet",
    expect: "refuse",
    outcome: "not-actionable",
    message: message(
      "Pending Offer Approval",
      "| | ## ACTION REQUIRED: Pending Offer Approval\n\n| Hello Aimee, There is a pending offer for " +
        "Dayten Schureman (333520) to fill Requisition 3685. This offer is for the Gulfstream G200 First " +
        "Officer position. |"
    )
  },
  {
    label: "Pending Offer Expires Soon — a chase-up",
    expect: "refuse",
    outcome: "not-actionable",
    message: message(
      "Pending Offer Expires Soon",
      "| | ## ACTION REQUIRED: Pending Offer Expires Soon\n\n| Hello Aimee, A pending offer for Dayten " +
        "Schureman (333520) to fill requisition 3685 expires soon. This offer is for the Gulfstream G200 " +
        "First Officer position. |"
    )
  },
  {
    label: "right subject, but the body describes an APPROVAL",
    expect: "refuse",
    message: message(
      "Offer Accepted",
      "Hello Aimee, A pending offer for Dayten Schureman (333520) to fill requisition 3685 has been " +
        "approved. This offer is for the Gulfstream G200 First Officer position."
    )
  },

  // ---------- routed copies: a Front rule puts these in a shared inbox ----------
  // Paycom addresses the notice to one person, and it lands in that teammate's
  // PRIVATE inbox which the API token cannot read (403 by design). A Front rule
  // copies it into HR Onboarding; whether the copy keeps Paycom as its sender,
  // gains a "Fwd:", or is marked outbound is up to Front's rule engine.
  {
    label: "routed: rule moved the conversation, sender preserved",
    expect: "recognise",
    kind: "OFFER_ACCEPTED",
    message: message("Offer Accepted", ACCEPTED_BODY)
  },
  {
    label: "routed: forwarded with a Fwd: prefix",
    expect: "recognise",
    kind: "OFFER_ACCEPTED",
    message: message("Fwd: Offer Accepted", forwarded("Offer Accepted", ACCEPTED_BODY), "aschaedig@skyshare.com")
  },
  {
    label: "routed: forwarded, subject left verbatim",
    expect: "recognise",
    kind: "OFFER_ACCEPTED",
    message: message("Offer Accepted", forwarded("Offer Accepted", ACCEPTED_BODY), "aschaedig@skyshare.com")
  },
  {
    // Front can mark a rule-created copy OUTBOUND because a teammate's channel
    // produced it. The sweeps used to skip outbound wholesale, which would have
    // ignored the only copy the app can see.
    label: "routed: marked OUTBOUND by Front — must still be read",
    expect: "recognise",
    kind: "OFFER_ACCEPTED",
    message: message(
      "Fwd: Offer Accepted",
      forwarded("Offer Accepted", ACCEPTED_BODY),
      "aschaedig@skyshare.com",
      false
    )
  },
  {
    label: "routed: the footer alone is sufficient provenance",
    expect: "recognise",
    kind: "OFFER_ACCEPTED",
    message: message(
      "Fwd: Offer Accepted",
      "Hello Aimee Schaedig, The offer for Dayten Schureman (333520) to fill Requisition 3685 has been " +
        "accepted. This offer was for the Gulfstream G200 First Officer position. This notice was " +
        "automatically generated by paycomonline.com.",
      "noreply@somechannel.frontapp.com"
    )
  },
  {
    label: "routed: a forwarded Pending Offer Approved still must NOT tick",
    expect: "refuse",
    outcome: "not-actionable",
    message: message(
      "Fwd: ACTION REQUIRED: Pending Offer Approved",
      forwarded("ACTION REQUIRED: Pending Offer Approved", APPROVED_BODY),
      "aschaedig@skyshare.com"
    )
  },
  {
    // A human replying quotes the whole notice underneath. bareSubject strips
    // Fwd:/FW: but deliberately NOT Re:, which is what stops this.
    label: "routed: a REPLY quoting the notice must NOT tick",
    expect: "refuse",
    message: message(
      "Re: Fwd: Offer Accepted",
      `Thanks - I have got this one.\n\n${forwarded("Offer Accepted", ACCEPTED_BODY)}`,
      "hbyers@skyshare.com"
    )
  },
  {
    // Provenance is the only gate now, so this is the case that matters most.
    label: "no Paycom provenance anywhere must NOT tick",
    expect: "refuse",
    outcome: "not-a-paycom-notice",
    message: message(
      "Offer Accepted",
      "Hi team, the offer for Dayten Schureman (333520) has been accepted. Nice work everyone!",
      "hbyers@skyshare.com"
    )
  },

  // ---------- noise the sweep sees but must not flag ----------
  // These are classified as known-and-skipped rather than unreadable, so the
  // "Paycom changed its wording" alarm keeps meaning only that.
  {
    label: "noise: interview invitation (free-form subject, body is the marker)",
    expect: "refuse",
    outcome: "not-actionable",
    message: message(
      "Paxton Boyce - PDP or Base Support (In-person)",
      "SKYSHARE 16856 You have been invited to an interview. When: August 18th, 2026 01:00 PM Mountain Time."
    )
  },
  {
    label: "noise: Paycom task notification",
    expect: "refuse",
    outcome: "not-actionable",
    message: message("[PaycomOnline] Add Employee to 90iO Directory", "Please add the employee to the directory.")
  },
  {
    label: "noise: checklist notification",
    expect: "refuse",
    outcome: "not-actionable",
    message: message("Checklist Completed", "A checklist has been completed.")
  },

  // ---------- the alarm itself ----------
  {
    // If Paycom reworded "Offer Accepted", the ignore list must NOT swallow it.
    label: "ALARM: an unseen Paycom subject still reports as unrecognised",
    expect: "refuse",
    outcome: "unrecognised-subject",
    message: message(
      "Offer Rescinded",
      "The offer for Someone New (999999) to fill Requisition 1 has been rescinded."
    )
  },

  // ---------- the background-check notices must keep working ----------
  // Their own collision: both subjects contain "background check" and
  // "completed", and only one means clear-to-hire.
  {
    label: "regression: background check step 2 (information submitted)",
    expect: "recognise",
    kind: "BG_INFO_SUBMITTED",
    message: message(
      "Background Check Requested Information Completed",
      "TARA WARD has completed the background check.",
      "employmentscreening@paycomonline.com"
    )
  },
  {
    label: "regression: background check step 3 (clear to hire)",
    expect: "recognise",
    kind: "BG_CHECK_COMPLETE",
    message: message(
      "Background check is completed",
      "The background check for TARA WARD has been completed and is ready for review.",
      "employmentscreening@paycomonline.com"
    )
  }
];

async function main() {
  if (!process.env.DATABASE_URL) {
    console.log("NO DATABASE_URL — refusing to report a pass without the roster to match against.");
    process.exit(1);
  }

  let passed = 0;
  const failures: string[] = [];

  for (const testCase of CASES) {
    const result = await processPaycomMessage(testCase.message, { dryRun: true });
    const recognised = RECOGNISED.has(result.outcome);

    const problems: string[] = [];
    if (testCase.expect === "recognise") {
      if (!recognised) problems.push(`expected it to be recognised, got outcome=${result.outcome}`);
      if (testCase.kind && result.kind !== testCase.kind) {
        problems.push(`expected kind=${testCase.kind}, got ${result.kind ?? "none"}`);
      }
    } else if (recognised) {
      problems.push(`expected it to be REFUSED, but it was acted on (outcome=${result.outcome})`);
    }
    if (testCase.outcome && result.outcome !== testCase.outcome) {
      problems.push(`expected outcome=${testCase.outcome}, got ${result.outcome}`);
    }

    if (problems.length === 0) {
      passed += 1;
      console.log(`PASS  ${testCase.label}`);
    } else {
      failures.push(`${testCase.label}\n        ${problems.join("\n        ")}`);
      console.log(`FAIL  ${testCase.label}`);
      for (const p of problems) console.log(`        ${p}`);
    }
  }

  console.log(`\n${passed}/${CASES.length} passed`);
  if (failures.length) {
    console.log(`\n${failures.length} FAILED:`);
    for (const f of failures) console.log(`  - ${f}`);
    console.log(
      "\nIf you loosened a pattern in lib/paycom/notices.ts, read the comment on\n" +
        "OFFER_ACCEPTED before deciding this test is wrong. Ticking the signed-offer\n" +
        "step off the wrong notice puts false compliance state on a real person."
    );
    process.exit(1);
  }
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
