import { prisma } from "@/lib/prisma";
import { getUserCalendar } from "@/lib/google/user-calendar";
import { isAuthRequired } from "@/lib/auth/auth-config";

/**
 * The Debrief Queue — interviews that HAPPENED on the recruiter's own Google
 * Calendar and still have no write-up in the app.
 *
 * Why this exists: interviews are run in Paycom, which blocks every integration,
 * so the notes are copied across by hand afterwards (see
 * POST /api/candidates/[id]/interviews). Nothing was reminding anyone to do it,
 * and the app CANNOT work it out from its own data — an Interview row is created
 * BY the act of writing up, so the table has never held a single future
 * interview. Measured Aug 17: 309 rows, 0 upcoming. The calendar is the only
 * thing that knows an interview took place.
 *
 * DETECTION DOES NOT LOOK AT THE TITLE, and that is deliberate. Measured over a
 * real 154-event, three-week window on aschaedig@:
 *   - 46 events contain the word "interview" and NOT ONE is an interview. They
 *     are all "[15-minute buffer before Recruiter 30 min Phone Interview event]"
 *     padding generated by the booking tool.
 *   - The 23 real interviews never say "interview" anywhere in the title.
 * So a keyword match would score 46 false positives and 23 misses. The shape of
 * the invite is what identifies it instead, and on that same window the shape
 * rule below found all 23 with no false positives.
 */

/** Anything at this domain is one of us, so it cannot be the candidate. */
export const INTERNAL_EMAIL_DOMAIN = "@skyshare.com";

/** How far back the queue looks. Three weeks covered the whole real backlog. */
export const DEBRIEF_WINDOW_DAYS = 21;

/** Dismissals live in the existing key-value store — no migration on the shared live DB. */
export const DEBRIEF_SETTING_SCOPE = "interviews";
export const DEBRIEF_SETTING_KEY = "debrief-dismissals";

/**
 * How close a write-up's date has to be to the calendar event to count as
 * "this one has been done".
 *
 * Generous on purpose: the write-up form takes a DATE, not a time, so its
 * startDateTime can land on midnight in either timezone, and a recruiter typing
 * up yesterday's interview may pick either day. The cost of being too tight is a
 * row that nags forever after the work is done, which is what kills trust in a
 * reminder. The cost of being too loose is two interviews with the SAME person
 * inside 36 hours sharing one write-up — rare, and visible on the profile.
 */
const WRITE_UP_MATCH_WINDOW_MS = 36 * 60 * 60 * 1000;

const TIMEZONE = "America/Denver";

/** Only the fields of a Google event this module reads. */
export type RawCalendarEvent = {
  id?: string | null;
  summary?: string | null;
  status?: string | null;
  htmlLink?: string | null;
  organizer?: { email?: string | null } | null;
  start?: { dateTime?: string | null; date?: string | null } | null;
  attendees?: Array<{
    email?: string | null;
    displayName?: string | null;
    resource?: boolean | null;
  }> | null;
};

export type DetectedInterview = {
  eventId: string;
  startsAt: Date;
  title: string;
  /** The one attendee who is not us. The exact key — never a name. */
  candidateEmail: string;
  attendeeName: string | null;
  /** Parsed from the title for DISPLAY and prefill only. */
  parsedName: string;
  parsedRole: string | null;
  htmlLink: string | null;
};

function isResourceAttendee(a: { email?: string | null; resource?: boolean | null }): boolean {
  if (a.resource) return true;
  return /resource\.calendar\.google\.com$/i.test(a.email ?? "");
}

function isInternal(email: string): boolean {
  return email.toLowerCase().endsWith(INTERNAL_EMAIL_DOMAIN);
}

/**
 * Every real interview is titled "Candidate Name-Role" — "Ken Figg-CL35 Captain
 * SLC", "Elmaz Tahirovic - CJ PIC Georgia".
 *
 * Splitting on the first dash is WRONG, and the real calendar says so:
 * "Jon-Micheal McKoy-PC12 PIC" would give the name "Jon" and the role
 * "Micheal McKoy-PC12 PIC". Splitting on the LAST dash is worse — roles are full
 * of them ("PC-12 Captain", "G-200 First Officer", "PDP SIC - Base Support").
 *
 * So: take the FIRST dash whose left side is a plausible full name, meaning two
 * or more words. That reads every title in the observed window correctly,
 * hyphenated first names included. A genuinely one-word name falls back to the
 * first dash rather than swallowing the role.
 *
 * Display and prefill only — matching is always by email, never by this.
 */
export function splitInterviewTitle(title: string): { name: string; role: string | null } {
  const raw = (title ?? "").trim();
  if (!raw.includes("-")) return { name: raw, role: null };

  const wordCount = (s: string) => s.trim().split(/\s+/).filter(Boolean).length;

  let chosen = -1;
  for (let i = raw.indexOf("-"); i !== -1; i = raw.indexOf("-", i + 1)) {
    if (wordCount(raw.slice(0, i)) >= 2) {
      chosen = i;
      break;
    }
  }
  if (chosen === -1) chosen = raw.indexOf("-");

  const name = raw.slice(0, chosen).trim();
  const role = raw.slice(chosen + 1).trim();
  return { name: name || raw, role: role || null };
}

/**
 * The shape rule: a timed event the owner organised, with exactly two human
 * attendees, exactly one of whom is outside the company.
 *
 * Each clause is carrying its weight against the real calendar:
 *  - timed only        → drops all-day markers ("Robert Patrick Visiting!!!")
 *  - organised by them → drops interviews on someone else's calendar they attend
 *  - exactly 2 humans  → drops the 5-person "Dinner with Robert and Rachelle!",
 *                        which otherwise passes every other test
 *  - exactly 1 outsider→ drops internal meetings, and 35 FOCUS_TIME blocks and
 *                        64 attendee-less to-dos fall out here for free
 */
export function detectInterviewEvents(
  events: RawCalendarEvent[],
  ownerEmail: string
): DetectedInterview[] {
  const owner = ownerEmail.toLowerCase();
  const found: DetectedInterview[] = [];

  for (const event of events) {
    if (!event.id) continue;
    if (event.status === "cancelled") continue;

    const startsAtRaw = event.start?.dateTime;
    if (!startsAtRaw) continue;
    const startsAt = new Date(startsAtRaw);
    if (Number.isNaN(startsAt.getTime())) continue;

    if ((event.organizer?.email ?? "").toLowerCase() !== owner) continue;

    const humans = (event.attendees ?? []).filter((a) => !isResourceAttendee(a));
    if (humans.length !== 2) continue;

    const outsiders = humans.filter((a) => a.email && !isInternal(a.email));
    if (outsiders.length !== 1) continue;

    const candidateEmail = outsiders[0].email;
    if (!candidateEmail) continue;

    const title = event.summary ?? "";
    const { name, role } = splitInterviewTitle(title);

    found.push({
      eventId: event.id,
      startsAt,
      title,
      candidateEmail: candidateEmail.toLowerCase(),
      attendeeName: outsiders[0].displayName ?? null,
      parsedName: name,
      parsedRole: role,
      htmlLink: event.htmlLink ?? null,
    });
  }

  return found;
}

/** YYYY-MM-DD in Mountain time. A UTC day key would roll over at 6pm local. */
export function denverDayKey(date: Date): string {
  return new Intl.DateTimeFormat("en-CA", {
    timeZone: TIMEZONE,
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  }).format(date);
}

/** Whole days between two instants, counted by Mountain calendar day. */
export function ageInDays(startsAt: Date, now: Date): number {
  const a = Date.parse(denverDayKey(startsAt) + "T00:00:00Z");
  const b = Date.parse(denverDayKey(now) + "T00:00:00Z");
  return Math.max(0, Math.round((b - a) / 86_400_000));
}

/**
 * Whose calendar to read.
 *
 * Normally the signed-in user's own, which is what makes a second recruiter work
 * later with no change here.
 *
 * Local dev bypasses auth, so there is no session and no OAuth identity — which
 * meant the queue could not be looked at on a laptop AT ALL before deploying it,
 * and the first person to open it saw an empty page and a blocker. This borrows
 * the token that account already stored from its own real sign-ins.
 *
 * SAFETY: gated on isAuthRequired() being FALSE. lib/auth/auth-config.ts only
 * returns false when NODE_ENV is development AND neither VERCEL nor VERCEL_ENV is
 * set, and REQUIRE_AUTH=true overrides even that — so this cannot engage on any
 * hosted deployment. It is a local viewing aid, never an auth path.
 */
export function resolveCalendarOwner(sessionEmail: string | null | undefined): string | null {
  if (sessionEmail) return sessionEmail;
  if (isAuthRequired()) return null;
  return process.env.DEBRIEF_DEV_CALENDAR_EMAIL?.trim() || null;
}

export type DebriefDismissal = {
  eventId: string;
  reason: string;
  at: string;
  by: string | null;
};

export async function readDismissals(): Promise<DebriefDismissal[]> {
  const row = await prisma.workspaceSetting.findUnique({
    where: { scope_key: { scope: DEBRIEF_SETTING_SCOPE, key: DEBRIEF_SETTING_KEY } },
  });
  if (!row) return [];
  try {
    const parsed = JSON.parse(row.valueJson);
    if (!Array.isArray(parsed)) return [];
    return parsed.filter((d): d is DebriefDismissal => Boolean(d && typeof d.eventId === "string"));
  } catch {
    // A corrupt value must not take the whole queue down with it.
    return [];
  }
}

async function writeDismissals(all: DebriefDismissal[]): Promise<void> {
  const valueJson = JSON.stringify(all);
  await prisma.workspaceSetting.upsert({
    where: { scope_key: { scope: DEBRIEF_SETTING_SCOPE, key: DEBRIEF_SETTING_KEY } },
    create: { scope: DEBRIEF_SETTING_SCOPE, key: DEBRIEF_SETTING_KEY, valueJson },
    update: { valueJson },
  });
}

/**
 * Hide events from the queue for good. Reversible — see restoreDismissal.
 *
 * TAKES A BATCH, and that is a correctness requirement rather than a convenience:
 * every dismissal lives in ONE WorkspaceSetting row as a JSON array, so each save
 * is a read-modify-write of the whole list. Clearing ten rows as ten concurrent
 * requests would have each one read the same starting state and the last writer
 * would win, silently losing the other nine. One request, one write.
 */
export async function dismissEvents(
  entries: Array<{ eventId: string; reason: string }>,
  by: string | null
): Promise<number> {
  const incoming = new Map(
    entries.filter((e) => e.eventId).map((e) => [e.eventId, e.reason] as const)
  );
  if (!incoming.size) return 0;

  const all = await readDismissals();
  const kept = all.filter((d) => !incoming.has(d.eventId));
  const at = new Date().toISOString();
  for (const [eventId, reason] of incoming) kept.push({ eventId, reason, at, by });
  await writeDismissals(kept);
  return incoming.size;
}

/** Single-event convenience over dismissEvents. */
export async function dismissEvent(eventId: string, reason: string, by: string | null): Promise<void> {
  await dismissEvents([{ eventId, reason }], by);
}

export async function restoreDismissal(eventId: string): Promise<void> {
  const all = await readDismissals();
  await writeDismissals(all.filter((d) => d.eventId !== eventId));
}

export type DebriefRow = {
  eventId: string;
  startsAt: string;
  title: string;
  parsedName: string;
  parsedRole: string | null;
  candidateEmail: string;
  ageDays: number;
  htmlLink: string | null;
  /** Null when no candidate carries this email — he picks the person by hand. */
  candidate: { id: string; displayName: string; status: string | null } | null;
  dismissedReason: string | null;
};

export type DebriefQueue = {
  /** Set when the calendar could not be read. Says what to DO about it. */
  blocker: string | null;
  calendarEmail: string | null;
  windowDays: number;
  scanned: number;
  detected: number;
  writtenUp: number;
  pending: DebriefRow[];
  unmatched: DebriefRow[];
  dismissed: DebriefRow[];
};

const emptyQueue = (blocker: string | null, windowDays: number): DebriefQueue => ({
  blocker,
  calendarEmail: null,
  windowDays,
  scanned: 0,
  detected: 0,
  writtenUp: 0,
  pending: [],
  unmatched: [],
  dismissed: [],
});

/**
 * Build the queue for whoever is signed in.
 *
 * Reads the "primary" calendar rather than a hard-coded address on purpose: it
 * is aschaedig@ today, and this is the whole of what makes it work for a second
 * recruiter later without touching this file.
 *
 * NOTE this only works signed in with Google on the real site. Local dev
 * bypasses auth, so there is no OAuth token to act as and the blocker below is
 * the expected local result, not a fault.
 */
export async function buildDebriefQueue(options: {
  ownerEmail: string | null | undefined;
  windowDays?: number;
  now?: Date;
}): Promise<DebriefQueue> {
  const windowDays = options.windowDays ?? DEBRIEF_WINDOW_DAYS;
  const now = options.now ?? new Date();

  const access = await getUserCalendar(options.ownerEmail);
  if (!access.client || !access.email) {
    return emptyQueue(access.blocker ?? "The calendar could not be read.", windowDays);
  }

  const timeMin = new Date(now.getTime() - windowDays * 86_400_000);
  let events: RawCalendarEvent[] = [];
  try {
    const response = await access.client.events.list({
      calendarId: "primary",
      timeMin: timeMin.toISOString(),
      timeMax: now.toISOString(),
      singleEvents: true,
      orderBy: "startTime",
      maxResults: 250,
      timeZone: TIMEZONE,
    });
    events = (response.data.items ?? []) as RawCalendarEvent[];
  } catch (error) {
    const message = error instanceof Error ? error.message : "Unknown error";
    return emptyQueue(`Google refused the calendar request: ${message}`, windowDays);
  }

  const detected = detectInterviewEvents(events, access.email);
  const dismissals = new Map(
    (await readDismissals()).map((d) => [d.eventId, d] as const)
  );

  // Match on email, in two queries rather than one per row.
  const emails = [...new Set(detected.map((d) => d.candidateEmail))];
  const candidates = emails.length
    ? await prisma.candidate.findMany({
        where: { OR: [{ normalizedEmail: { in: emails } }, { primaryEmail: { in: emails } }] },
        select: { id: true, displayName: true, status: true, primaryEmail: true, normalizedEmail: true },
      })
    : [];

  const byEmail = new Map<string, { id: string; displayName: string; status: string | null }>();
  for (const c of candidates) {
    const row = { id: c.id, displayName: c.displayName, status: c.status };
    if (c.normalizedEmail) byEmail.set(c.normalizedEmail.toLowerCase(), row);
    if (c.primaryEmail) byEmail.set(c.primaryEmail.toLowerCase(), row);
  }

  // Every write-up in the window for the matched people, in one query.
  const candidateIds = [...new Set([...byEmail.values()].map((c) => c.id))];
  const writeUps = candidateIds.length
    ? await prisma.interview.findMany({
        where: {
          candidateId: { in: candidateIds },
          startDateTime: {
            gte: new Date(timeMin.getTime() - WRITE_UP_MATCH_WINDOW_MS),
            lte: new Date(now.getTime() + WRITE_UP_MATCH_WINDOW_MS),
          },
        },
        select: { candidateId: true, startDateTime: true, notes: true, notesHtml: true },
      })
    : [];

  const written = writeUps.filter(
    (w) => (w.notes && w.notes.trim().length > 0) || (w.notesHtml && w.notesHtml.trim().length > 0)
  );

  const queue: DebriefQueue = {
    blocker: null,
    calendarEmail: access.email,
    windowDays,
    scanned: events.length,
    detected: detected.length,
    writtenUp: 0,
    pending: [],
    unmatched: [],
    dismissed: [],
  };

  for (const item of detected) {
    const candidate = byEmail.get(item.candidateEmail) ?? null;
    const dismissal = dismissals.get(item.eventId) ?? null;

    const row: DebriefRow = {
      eventId: item.eventId,
      startsAt: item.startsAt.toISOString(),
      title: item.title,
      parsedName: item.parsedName,
      parsedRole: item.parsedRole,
      candidateEmail: item.candidateEmail,
      ageDays: ageInDays(item.startsAt, now),
      htmlLink: item.htmlLink,
      candidate,
      dismissedReason: dismissal?.reason ?? null,
    };

    if (candidate) {
      const done = written.some(
        (w) =>
          w.candidateId === candidate.id &&
          Math.abs(w.startDateTime.getTime() - item.startsAt.getTime()) <= WRITE_UP_MATCH_WINDOW_MS
      );
      if (done) {
        queue.writtenUp += 1;
        continue;
      }
    }

    if (dismissal) {
      queue.dismissed.push(row);
    } else if (candidate) {
      queue.pending.push(row);
    } else {
      queue.unmatched.push(row);
    }
  }

  // Oldest first — the ones rotting longest are the ones being forgotten.
  const oldestFirst = (a: DebriefRow, b: DebriefRow) => a.startsAt.localeCompare(b.startsAt);
  queue.pending.sort(oldestFirst);
  queue.unmatched.sort(oldestFirst);
  queue.dismissed.sort(oldestFirst);

  return queue;
}
